version: "3.9"

networks:
  web:

volumes:
  db:

services:
  app:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - web

  php:
    build:
      context: docker/php
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    command: php-fpm
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - web

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db:/var/lib/mysql
    networks:
      - web

  yarn:
    image: node:lts-alpine
    volumes:
      - .:/var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www/html
    networks:
      - web
